# App Config
# Key: config/const.go
# Default: config/config.go#setDefault()

server:
  host: "0.0.0.0"
  port: 8080
  read-timeout: 15s
  write-timeout: 15s
  request-timeout: 10s
  max-shutdown-duration: 30s
  pprof-token: "<change me>"
  cors:
    allow-origins:
      - "*"

# github.com/litsea/log-slog
log:
  handlers:
    - console
    - file
    - sentry
  console:
    handler: text
    output: stdout
    level: debug
  file:
    handler: json
    output: file
    filename: tmp/log/app.log
    level: info
    max-days: 5
    max-mbs: 10
    max-backups: 5
  sentry:
    handler: sentry
    dsn: ""
    env: local
    debug: true
