# App Config
# Key: config/const.go
# Default: config/config.go#setDefault()

env: local

server:
  host: "0.0.0.0"
  port: 8080
  # pprof-token: "<change me>"
  cors:
    allow-origins:
      - "*"

# github.com/litsea/log-slog
log:
  handlers:
    - console
    - sentry
  console:
    handler: text
    output: stdout
    level: debug
  sentry:
    handler: sentry
    dsn: ""
    env: local
    debug: false
